name = "OrthancTools"
uuid = "d6a53a69-57dd-4bf1-83cc-71c4a7042fcf"
authors = ["Dale-Black <djblack@uci.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
